# Generated by Django 5.0.3 on 2024-03-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='userType',
            field=models.CharField(default='', max_length=6),
        ),
    ]
