# Generated by Django 5.0.3 on 2024-04-13 08:01

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser_phone_appuser_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('itemBrand', models.CharField(max_length=50)),
                ('itemModel', models.CharField(max_length=100)),
                ('itemCategory', models.CharField(max_length=50)),
                ('itemType', models.CharField(max_length=50)),
                ('isBrandNew', models.BooleanField()),
                ('usedPeriod', models.IntegerField(blank=True, null=True)),
                ('itemDescription', models.CharField(max_length=1000)),
                ('itemImage', models.ImageField(default='item/default.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
                ('startingPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currentPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('isSold', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateDate', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidder', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
