# Generated by Django 5.0.3 on 2024-04-13 08:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_biditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='itemImage',
            field=models.ImageField(default='items/default.jpg', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
