# Generated by Django 5.0.3 on 2024-04-13 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_biditem_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='bidder',
            field=models.ForeignKey(blank=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='currentPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
