# Generated by Django 5.0.3 on 2024-04-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_biditem_currentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='itemVariant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
