# Generated by Django 5.0.3 on 2024-04-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_biditem_itemvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='isPendingPayment',
            field=models.BooleanField(default=False),
        ),
    ]
